"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, FilePlus2, Loader2, Palette, RefreshCw } from "lucide-react";
import { usePatients } from "@/components/patients/patient-provider";
import { EmptyState, ErrorAlert, LoadingState, Modal, StatusBadge } from "@/components/ui/workspace-ui";
import { CrudPageHeader, MetricCards } from "@/components/ui/crud-ui";
import { displayDate, platformRequest, recordList, type PlatformRecord } from "@/lib/platform-client";
import { fullName } from "@/lib/patients";

export function DocumentsWorkspace() {
  const {patients,ready}=usePatients(); const [rows,setRows]=useState<PlatformRecord[]>([]),[templates,setTemplates]=useState<PlatformRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[formError,setFormError]=useState("");
  const [values,setValues]=useState({patientId:"",title:"Plan nutricional",documentType:"meal_plan",patientDisplayName:"",templateId:"",summary:"Plan personalizado elaborado según la evaluación nutricional.",organizationName:"NUTRIMEJOR",primaryColor:"#1F7A5A",footer:"Nutrición con propósito"});
  const load=useCallback(async()=>{try{setLoading(true);const [documents,available]=await Promise.all([platformRequest("/api/platform/documents/generated-documents"),platformRequest("/api/platform/documents/templates")]);setRows(recordList(documents));setTemplates(recordList(available));}catch(e){setError(e instanceof Error?e.message:"No se cargaron los documentos.");}finally{setLoading(false);}},[]); useEffect(()=>{void load();},[load]);
  async function save(event:React.FormEvent){event.preventDefault();const patient=patients.find((item)=>item.id===values.patientId);if(!patient||!values.title.trim()){setFormError("Selecciona el paciente y escribe el título.");return;}try{setSaving(true);setFormError("");let templateId=values.templateId;if(!templateId){const template=await platformRequest<PlatformRecord>("/api/platform/documents/templates",{method:"POST",body:JSON.stringify({name:`Identidad ${values.organizationName}`,documentType:values.documentType,definition:{organizationName:values.organizationName,primaryColor:values.primaryColor,footer:values.footer}})});templateId=template.id;}await platformRequest("/api/platform/documents/generated-documents",{method:"POST",body:JSON.stringify({patientId:values.patientId,title:values.title,documentType:values.documentType,templateId,patientDisplayName:fullName(patient),sections:[{type:"heading",text:values.title},{type:"paragraph",text:values.summary},{type:"key_value",items:[{label:"Paciente",value:fullName(patient)},{label:"Fecha",value:new Intl.DateTimeFormat("es-BO").format(new Date())},{label:"Documento",value:documentTypeLabel(values.documentType)}]}]})});setOpen(false);await load();}catch(e){setFormError(e instanceof Error?e.message:"No se pudo generar el PDF.");}finally{setSaving(false);}}
  async function download(row:PlatformRecord){try{const result=await platformRequest<{url:string}>(`/api/platform/documents/generated-documents/${row.id}/access-url`,{method:"POST",body:JSON.stringify({expiresInMinutes:15})});const token=result.url.split("/").pop();window.open(`/api/platform/documents/download/${encodeURIComponent(token||"")}`,"_blank","noopener,noreferrer");}catch(e){setError(e instanceof Error?e.message:"El PDF todavía no está disponible.");}}
  return <section><CrudPageHeader eyebrow="PDF con identidad visual" title="Documentos" description="Genera documentos con el nombre, color y pie de página del consultorio." action={<button className="primary-button" onClick={()=>setOpen(true)}><FilePlus2 className="h-4 w-4"/>Generar PDF</button>}/><MetricCards metrics={[{label:"Documentos",value:rows.length,detail:"Solicitudes generadas"},{label:"Listos",value:rows.filter((row)=>row.status==="completed").length,detail:"Disponibles para descargar",tone:"blue"},{label:"En proceso",value:rows.filter((row)=>["queued","processing"].includes(String(row.status))).length,detail:"Generación pendiente",tone:"amber"},{label:"Plantillas",value:templates.length,detail:"Identidades disponibles",tone:"slate"}]}/>{error&&<ErrorAlert message={error} onRetry={()=>void load()}/>}<div className="card mt-6 overflow-hidden">{loading||!ready?<LoadingState/>:!rows.length?<EmptyState title="Sin documentos" detail="Genera el primer PDF para un paciente."/>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-emerald-950"><tr><th className="p-4">Documento</th><th>Paciente</th><th>Fecha</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{rows.map((row)=><tr className="border-t dark:border-emerald-800" key={row.id}><td className="p-4 font-semibold">{String(row.title)}</td><td>{patients.find((p)=>p.id===row.patientId)?fullName(patients.find((p)=>p.id===row.patientId)!):"Paciente"}</td><td>{displayDate(row.requestedAt)}</td><td><StatusBadge value={row.status}/></td><td>{row.status==="completed"?<button className="secondary-button" onClick={()=>void download(row)}><Download className="h-4 w-4"/>Descargar</button>:<button className="secondary-button" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Actualizar</button>}</td></tr>)}</tbody></table></div>}</div>
    {open&&<Modal title="Generar PDF institucional" description="Puedes reutilizar una plantilla o definir una nueva identidad visual." onClose={()=>setOpen(false)}><form className="mt-5 grid gap-4" onSubmit={save}><label>Paciente *<select className="field" value={values.patientId} onChange={(e)=>{const patient=patients.find((p)=>p.id===e.target.value);setValues({...values,patientId:e.target.value,patientDisplayName:patient?fullName(patient):""});}}><option value="">Selecciona</option>{patients.map((p)=><option value={p.id} key={p.id}>{fullName(p)}</option>)}</select></label><label>Título *<input className="field" value={values.title} onChange={(e)=>setValues({...values,title:e.target.value})}/></label><label>Tipo<select className="field" value={values.documentType} onChange={(e)=>setValues({...values,documentType:e.target.value,templateId:""})}><option value="meal_plan">Plan alimentario</option><option value="progress_report">Reporte de evolución</option><option value="clinical_summary">Resumen clínico</option><option value="recommendations">Recomendaciones</option></select></label><label>Plantilla existente (opcional)<select className="field" value={values.templateId} onChange={(e)=>setValues({...values,templateId:e.target.value})}><option value="">Crear con esta identidad</option>{templates.filter((t)=>t.documentType===values.documentType).map((t)=><option value={t.id} key={t.id}>{String(t.name)}</option>)}</select></label>{!values.templateId&&<fieldset className="rounded-xl border p-4 dark:border-emerald-800"><legend className="flex items-center gap-2 px-2 font-semibold"><Palette className="h-4 w-4"/>Identidad del consultorio</legend><label>Nombre<input className="field" value={values.organizationName} onChange={(e)=>setValues({...values,organizationName:e.target.value})}/></label><div className="mt-3 grid grid-cols-[1fr_5rem] gap-3"><label>Pie de página<input className="field" value={values.footer} onChange={(e)=>setValues({...values,footer:e.target.value})}/></label><label>Color<input aria-label="Color principal" className="field h-11 p-1" type="color" value={values.primaryColor} onChange={(e)=>setValues({...values,primaryColor:e.target.value})}/></label></div></fieldset>}<label>Contenido principal<textarea rows={5} className="field py-3" value={values.summary} onChange={(e)=>setValues({...values,summary:e.target.value})}/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{saving?"Encolando…":"Generar documento"}</button></form></Modal>}
  </section>;
}
function documentTypeLabel(value:string){return ({meal_plan:"Plan alimentario",progress_report:"Reporte de evolución",clinical_summary:"Resumen clínico",recommendations:"Recomendaciones"} as Record<string,string>)[value]||value;}
