"use client";

import { useEffect, useState } from "react";
import { Loader2, Plus, Target } from "lucide-react";
import { EmptyState, ErrorAlert, Modal, StatusBadge } from "@/components/ui/workspace-ui";
import { displayDate, platformRequest, recordList, type PlatformRecord } from "@/lib/platform-client";

export function GoalsWorkspace() {
  const [consultations,setConsultations]=useState<PlatformRecord[]>([]),[consultationId,setConsultationId]=useState(""),[goals,setGoals]=useState<PlatformRecord[]>([]),[followUps,setFollowUps]=useState<PlatformRecord[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  const [mode,setMode]=useState<"goal"|"progress"|null>(null),[saving,setSaving]=useState(false),[formError,setFormError]=useState("");
  const [goal,setGoal]=useState({title:"",description:"",targetValue:"",unit:"kg",dueDate:""}),[progress,setProgress]=useState({summary:"",adherence:"",difficulties:"",nextSteps:"",scheduledAt:""});
  useEffect(()=>{platformRequest("/api/platform/clinical/consultations").then((v)=>{const list=recordList(v);setConsultations(list);setConsultationId(list[0]?.id||"");}).catch((e)=>setError(e instanceof Error?e.message:"No se cargaron las consultas."));},[]);
  useEffect(()=>{if(!consultationId){setGoals([]);setFollowUps([]);return;}setLoading(true);Promise.all([platformRequest(`/api/platform/clinical/consultations/${consultationId}/goals`),platformRequest(`/api/platform/clinical/consultations/${consultationId}/follow-ups`)]).then(([g,f])=>{setGoals(recordList(g));setFollowUps(recordList(f));}).catch((e)=>setError(e instanceof Error?e.message:"No se cargó el seguimiento.")).finally(()=>setLoading(false));},[consultationId]);
  async function reload(){const [g,f]=await Promise.all([platformRequest(`/api/platform/clinical/consultations/${consultationId}/goals`),platformRequest(`/api/platform/clinical/consultations/${consultationId}/follow-ups`)]);setGoals(recordList(g));setFollowUps(recordList(f));}
  async function saveGoal(event:React.FormEvent){event.preventDefault();if(!goal.title.trim()){setFormError("Escribe el objetivo.");return;}try{setSaving(true);setFormError("");await platformRequest(`/api/platform/clinical/consultations/${consultationId}/goals`,{method:"POST",body:JSON.stringify({title:goal.title,description:goal.description||null,targetValue:goal.targetValue?Number(goal.targetValue):null,unit:goal.unit||null,dueDate:goal.dueDate?new Date(goal.dueDate).toISOString():null,status:"active"})});setMode(null);setGoal({title:"",description:"",targetValue:"",unit:"kg",dueDate:""});await reload();}catch(e){setFormError(e instanceof Error?e.message:"No se guardó el objetivo.");}finally{setSaving(false);}}
  async function saveProgress(event:React.FormEvent){event.preventDefault();if(!progress.summary.trim()){setFormError("Describe el avance observado.");return;}try{setSaving(true);setFormError("");await platformRequest(`/api/platform/clinical/consultations/${consultationId}/follow-ups`,{method:"POST",body:JSON.stringify({summary:progress.summary,adherence:progress.adherence?Number(progress.adherence):null,difficulties:progress.difficulties||null,nextSteps:progress.nextSteps||null,scheduledAt:progress.scheduledAt?new Date(progress.scheduledAt).toISOString():null})});setMode(null);setProgress({summary:"",adherence:"",difficulties:"",nextSteps:"",scheduledAt:""});await reload();}catch(e){setFormError(e instanceof Error?e.message:"No se guardó el seguimiento.");}finally{setSaving(false);}}
  return <section className="mt-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Seguimiento</p><h2 className="mt-2 font-display text-2xl font-bold">Objetivos nutricionales</h2><p className="mt-1 text-sm text-slate-500">Define metas medibles y registra adherencia, dificultades y próximos pasos.</p></div><div className="flex flex-wrap gap-2"><button className="secondary-button" disabled={!consultationId} onClick={()=>{setFormError("");setMode("progress");}}>Registrar avance</button><button className="primary-button" disabled={!consultationId} onClick={()=>{setFormError("");setMode("goal");}}><Plus className="h-4 w-4"/>Nuevo objetivo</button></div></div>{error&&<ErrorAlert message={error}/>}<label className="mt-5 block max-w-xl text-sm font-semibold">Consulta de referencia<select className="field" value={consultationId} onChange={(e)=>setConsultationId(e.target.value)}><option value="">Selecciona una consulta</option>{consultations.map((item)=><option value={item.id} key={item.id}>{String(item.title)} · {displayDate(item.occurredAt||item.createdAt)}</option>)}</select></label>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card p-5"><h3 className="flex items-center gap-2 font-display font-bold"><Target className="h-5 w-5 text-emerald-700"/>Metas activas</h3>{loading?<p className="mt-4 text-sm text-slate-500">Cargando…</p>:!goals.length?<EmptyState title="Sin objetivos" detail="Crea una meta clínica medible para iniciar su seguimiento."/>:<div className="mt-4 space-y-3">{goals.map((item)=><article className="rounded-xl border p-4 dark:border-emerald-800" key={item.id}><div className="flex justify-between gap-2"><strong>{String(item.title)}</strong><StatusBadge value={item.status}/></div>{item.targetValue!=null&&<p className="mt-2 text-lg font-bold text-emerald-700">{String(item.targetValue)} {String(item.unit||"")}</p>}<p className="text-sm text-slate-500">{String(item.description||"Sin descripción")}</p>{Boolean(item.dueDate)&&<small>Meta: {displayDate(item.dueDate)}</small>}</article>)}</div>}</div><div className="card p-5"><h3 className="font-display font-bold">Historial de avances</h3>{!followUps.length?<EmptyState title="Sin seguimientos" detail="Registra el primer control de adherencia."/>:<ol className="mt-4 space-y-3">{followUps.map((item)=><li className="border-l-2 border-emerald-500 pl-4" key={item.id}><strong className="text-sm">{String(item.summary)}</strong>{item.adherence!=null&&<p className="text-sm text-emerald-700">Adherencia: {String(item.adherence)}%</p>}<small className="text-slate-500">{displayDate(item.createdAt)}</small></li>)}</ol>}</div></div>
    {mode==="goal"&&<Modal title="Nuevo objetivo nutricional" onClose={()=>setMode(null)}><form className="mt-5 grid gap-4" onSubmit={saveGoal}><label>Objetivo *<input className="field" value={goal.title} onChange={(e)=>setGoal({...goal,title:e.target.value})}/></label><label>Descripción<textarea className="field py-3" value={goal.description} onChange={(e)=>setGoal({...goal,description:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label>Valor meta<input className="field" type="number" step="0.1" value={goal.targetValue} onChange={(e)=>setGoal({...goal,targetValue:e.target.value})}/></label><label>Unidad<input className="field" value={goal.unit} onChange={(e)=>setGoal({...goal,unit:e.target.value})}/></label></div><label>Fecha objetivo<input className="field" type="datetime-local" value={goal.dueDate} onChange={(e)=>setGoal({...goal,dueDate:e.target.value})}/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Guardar objetivo</button></form></Modal>}
    {mode==="progress"&&<Modal title="Registrar avance" onClose={()=>setMode(null)}><form className="mt-5 grid gap-4" onSubmit={saveProgress}><label>Resumen del avance *<textarea className="field py-3" value={progress.summary} onChange={(e)=>setProgress({...progress,summary:e.target.value})}/></label><label>Adherencia (%)<input className="field" type="number" min="0" max="100" value={progress.adherence} onChange={(e)=>setProgress({...progress,adherence:e.target.value})}/></label><label>Dificultades<textarea className="field py-3" value={progress.difficulties} onChange={(e)=>setProgress({...progress,difficulties:e.target.value})}/></label><label>Próximos pasos<textarea className="field py-3" value={progress.nextSteps} onChange={(e)=>setProgress({...progress,nextSteps:e.target.value})}/></label><label>Próximo control<input className="field" type="datetime-local" value={progress.scheduledAt} onChange={(e)=>setProgress({...progress,scheduledAt:e.target.value})}/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Guardar seguimiento</button></form></Modal>}
  </section>;
}

