"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Loader2, Plus, Search } from "lucide-react";
import { EvolutionChart } from "@/components/charts/evolution-chart";
import { usePatients } from "@/components/patients/patient-provider";
import { EmptyState, ErrorAlert, LoadingState, Modal, Pagination, StatusBadge } from "@/components/ui/workspace-ui";
import { CrudPageHeader, MetricCards } from "@/components/ui/crud-ui";
import { dateInput, displayDate, platformRequest, recordList, type PlatformRecord } from "@/lib/platform-client";
import { fullName } from "@/lib/patients";

type Values = Record<string, string>;
const fields = [{ key: "weight", label: "Peso", unit: "kg" }, { key: "height", label: "Estatura", unit: "cm" }, { key: "waist", label: "Cintura", unit: "cm" }, { key: "hip", label: "Cadera", unit: "cm" }, { key: "arm_circumference", label: "Brazo", unit: "cm" }];
const bodyFields = [{ key: "body_fat_percent", label: "Grasa corporal", unit: "%" }, { key: "muscle_mass_kg", label: "Masa muscular", unit: "kg" }, { key: "body_water_percent", label: "Agua corporal", unit: "%" }];
const empty = (): Values => ({ patientId: "", title: "Control antropométrico", recordedAt: dateInput(), method: "Protocolo clínico básico", notes: "", weight: "", height: "", waist: "", hip: "", arm_circumference: "", body_fat_percent: "", muscle_mass_kg: "", body_water_percent: "" });

export function MeasurementWorkspace() {
  const { patients, ready } = usePatients();
  const [rows, setRows] = useState<PlatformRecord[]>([]), [details, setDetails] = useState<PlatformRecord[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [comparison, setComparison] = useState<PlatformRecord[]>([]), [comparisonLoading, setComparisonLoading] = useState(false);
  const [query, setQuery] = useState(""), [patientId, setPatientId] = useState(""), [page, setPage] = useState(1), [open, setOpen] = useState(false);
  const [values, setValues] = useState<Values>(empty), [formError, setFormError] = useState(""), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setLoading(true); setError(""); const list = recordList(await platformRequest("/api/platform/measurements/measurement-sessions")); setRows(list); const full = await Promise.all(list.map((row) => platformRequest<PlatformRecord>(`/api/platform/measurements/measurement-sessions/${row.id}`).catch(() => row))); setDetails(full); } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron cargar las mediciones."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!patientId) { setComparison([]); return; } setComparisonLoading(true); platformRequest(`/api/platform/measurements/patients/${patientId}/measurements/comparison`).then((value)=>setComparison(recordList(value))).catch((e)=>setError(e instanceof Error?e.message:"No se pudo comparar las mediciones.")).finally(()=>setComparisonLoading(false)); }, [patientId]);
  const filtered = useMemo(() => rows.filter((row) => (!patientId || row.patientId === patientId) && [row.title, row.status, fullName(patients.find((p) => p.id === row.patientId) || { names: "", lastNames: "" } as never)].join(" ").toLowerCase().includes(query.toLowerCase())), [rows, patientId, query, patients]);
  const pageSize=8, pages=Math.max(1,Math.ceil(filtered.length/pageSize)), visible=filtered.slice((page-1)*pageSize,page*pageSize);
  useEffect(() => setPage(1), [query, patientId]);
  async function save(event: React.FormEvent) { event.preventDefault(); const measurements=fields.filter((f)=>values[f.key]).map((f)=>({ type:f.key, value:Number(values[f.key]), unit:f.unit, ...(f.key === "arm_circumference" ? { side: "right" } : {}) })); const composition=bodyFields.filter((f)=>values[f.key]).map((f)=>({ indicator:f.key,value:Number(values[f.key]),unit:f.unit,method:values.method,formulaCode:"MANUAL",formulaVersion:"1.0.0",formulaSource:"Registro profesional",inputs:{} })); if(!values.patientId){setFormError("Selecciona un paciente.");return} if(!values.title.trim()){setFormError("Escribe un título.");return} if(!measurements.length&&!composition.length){setFormError("Registra al menos una medición.");return} if([...measurements,...composition].some((m)=>m.value<=0)){setFormError("Todas las mediciones deben ser mayores que cero.");return} try{setSaving(true);setFormError("");await platformRequest("/api/platform/measurements/measurement-sessions",{method:"POST",body:JSON.stringify({patientId:values.patientId,title:values.title.trim(),recordedAt:new Date(values.recordedAt).toISOString(),method:values.method,notes:values.notes,measurements,bodyComposition:composition})});setOpen(false);setValues(empty());await load()}catch(e){setFormError(e instanceof Error?e.message:"No se pudo guardar.")}finally{setSaving(false)} }
  const selected = patientId ? details.filter((row)=>row.patientId===patientId) : [];
  const points = (key:string, source:"measurements"|"bodyComposition"|"calculations") => selected.flatMap((row) => { const list = Array.isArray(row[source]) ? row[source] as Record<string,unknown>[] : []; const found=list.find((item)=>item.type===key||item.indicator===key||item.formulaCode===key); return found ? [{date:String(row.recordedAt||row.createdAt),value:Number(found.value??found.result)}] : []; });
  return <section><CrudPageHeader eyebrow="Seguimiento y evolución corporal" title="Mediciones" description="Registra antropometría y analiza los cambios clínicos a través del tiempo." action={<button className="primary-button" onClick={()=>{setValues(empty());setOpen(true)}}><Plus className="h-4 w-4"/>Nueva medición</button>}/><MetricCards metrics={[{label:"Sesiones",value:rows.length,detail:"Controles registrados"},{label:"Pacientes medidos",value:new Set(rows.map((row)=>row.patientId)).size,detail:"Con evolución",tone:"blue"},{label:"Comparaciones",value:comparison.length,detail:patientId?"Indicadores calculados":"Selecciona un paciente",tone:"amber"},{label:"Este mes",value:rows.filter((row)=>Date.now()-Date.parse(String(row.recordedAt||row.createdAt||0))<30*86_400_000).length,detail:"Actividad reciente",tone:"slate"}]}/>{error&&<ErrorAlert message={error} onRetry={()=>void load()}/>}<div className="card mt-5 overflow-hidden"><div className="grid gap-3 border-b p-4 dark:border-emerald-800 sm:grid-cols-[1fr_16rem] sm:p-5"><label className="relative"><span className="sr-only">Buscar mediciones</span><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400"/><input className="field !mt-0 pl-11" placeholder="Buscar control" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><label><span className="sr-only">Paciente para filtrar y graficar</span><select className="field !mt-0" value={patientId} onChange={(e)=>setPatientId(e.target.value)}><option value="">Todos los pacientes</option>{patients.map((p)=><option key={p.id} value={p.id}>{fullName(p)}</option>)}</select></label></div>{loading||!ready?<LoadingState/>:!visible.length?<EmptyState title="Sin mediciones" detail="Registra una sesión o cambia los filtros."/>:<><div className="overflow-x-auto"><table className="data-table w-full min-w-[650px] text-left text-sm"><thead><tr><th className="p-4">Control</th><th>Paciente</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>{visible.map((row)=><tr key={row.id}><td className="p-4 font-semibold">{String(row.title)}</td><td>{fullName(patients.find((p)=>p.id===row.patientId) || {names:"Paciente",lastNames:"no disponible"} as never)}</td><td>{displayDate(row.recordedAt||row.createdAt)}</td><td><StatusBadge value={row.status}/></td></tr>)}</tbody></table></div><Pagination page={page} pages={pages} total={filtered.length} onChange={setPage}/></>}</div>
    <div className="mt-8"><div className="mb-4"><h2 className="font-display text-2xl font-bold">Gráficas de evolución</h2><p className="mt-1 text-sm text-slate-500">Selecciona un paciente para comparar el primer control con el más reciente.</p></div>{!patientId?<EmptyState title="Selecciona un paciente" detail="Las series clínicas se muestran de forma individual para proteger la lectura de los datos."/>:<>{comparisonLoading?<LoadingState label="Comparando controles…"/>:comparison.length>0&&<div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{comparison.map((item)=>{const initial=Number(item.initialValue),current=Number(item.currentValue),change=current-initial,percent=initial?change/initial*100:0;return <article className="card p-4" key={`${item.metric}-${item.unit}`}><p className="text-sm text-slate-500">{metricLabel(String(item.metric))}</p><strong className="mt-1 block text-xl">{current.toFixed(1)} {String(item.unit)}</strong><span className={`text-sm font-semibold ${change===0?"text-slate-500":change<0?"text-emerald-700":"text-amber-700"}`}>{change>0?"+":""}{change.toFixed(1)} · {percent>0?"+":""}{percent.toFixed(1)}%</span><small className="block text-slate-400">Inicial: {initial.toFixed(1)} {String(item.unit)}</small></article>;})}</div>}<div className="grid gap-5 xl:grid-cols-2"><EvolutionChart title="Peso e IMC" unit="kg / IMC" series={[{label:"Peso",color:"#047857",points:points("weight","measurements")},{label:"IMC",color:"#2563eb",points:points("BMI","calculations")} ]}/><EvolutionChart title="Perímetros" unit="cm" series={[{label:"Cintura",color:"#047857",points:points("waist","measurements")},{label:"Cadera",color:"#7c3aed",points:points("hip","measurements")},{label:"Brazo",color:"#ea580c",points:points("arm_circumference","measurements")}]}/><EvolutionChart title="Composición corporal" unit="% / kg" series={[{label:"Grasa %",color:"#dc2626",points:points("body_fat_percent","bodyComposition")},{label:"Músculo kg",color:"#047857",points:points("muscle_mass_kg","bodyComposition")},{label:"Agua %",color:"#0284c7",points:points("body_water_percent","bodyComposition")}]}/></div></>}</div>
    {open&&<Modal title="Nueva sesión de medición" description="Puedes registrar antropometría básica o composición corporal." onClose={()=>setOpen(false)}><form className="mt-6 grid gap-4" onSubmit={save} noValidate><label>Paciente *<select className="field" value={values.patientId} onChange={(e)=>setValues({...values,patientId:e.target.value})}><option value="">Selecciona un paciente</option>{patients.map((p)=><option value={p.id} key={p.id}>{fullName(p)}</option>)}</select></label><label>Título *<input className="field" value={values.title} onChange={(e)=>setValues({...values,title:e.target.value})}/></label><label>Fecha y hora *<input type="datetime-local" className="field" value={values.recordedAt} onChange={(e)=>setValues({...values,recordedAt:e.target.value})}/></label><div><h3 className="font-semibold">Antropometría</h3><div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-3">{fields.map((f)=><label key={f.key} className="text-sm">{f.label} ({f.unit})<input className="field" type="number" min="0" step="0.01" value={values[f.key]} onChange={(e)=>setValues({...values,[f.key]:e.target.value})}/></label>)}</div></div><div><h3 className="font-semibold">Composición corporal</h3><div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-3">{bodyFields.map((f)=><label key={f.key} className="text-sm">{f.label} ({f.unit})<input className="field" type="number" min="0" step="0.01" value={values[f.key]} onChange={(e)=>setValues({...values,[f.key]:e.target.value})}/></label>)}</div></div><label>Método<input className="field" value={values.method} onChange={(e)=>setValues({...values,method:e.target.value})}/></label><label>Notas<textarea className="field py-3" rows={3} value={values.notes} onChange={(e)=>setValues({...values,notes:e.target.value})}/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button className="secondary-button" type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{saving?"Guardando…":"Guardar medición"}</button></div></form></Modal>}
  </section>;
}

function metricLabel(metric:string) { return ({ weight:"Peso",height:"Estatura",waist:"Cintura",hip:"Cadera",arm_circumference:"Brazo",BMI:"IMC","body_composition:body_fat_percent":"Grasa corporal","body_composition:muscle_mass_kg":"Masa muscular","body_composition:body_water_percent":"Agua corporal" } as Record<string,string>)[metric] || metric.replaceAll("_"," "); }
