"use client";

import { useState } from "react";
import { CheckCircle2, Loader2, RefreshCw } from "lucide-react";
import { Modal, StatusBadge } from "@/components/ui/workspace-ui";
import { dateInput, displayDate, platformRequest, type PlatformRecord } from "@/lib/platform-client";

export function PatientAppointments({ initialAppointments }: { initialAppointments: PlatformRecord[] }) {
  const [appointments,setAppointments]=useState(initialAppointments),[selected,setSelected]=useState<PlatformRecord|null>(null),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[reason,setReason]=useState("Solicitada desde el portal del paciente"),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const upcoming=appointments.filter((item)=>["scheduled","confirmed"].includes(String(item.status))&&new Date(String(item.startsAt)).getTime()>=Date.now()).sort((a,b)=>String(a.startsAt).localeCompare(String(b.startsAt)));
  async function confirm(item:PlatformRecord){try{setSaving(true);setError("");const updated=await platformRequest<PlatformRecord>(`/api/platform/scheduling/appointments/${item.id}/status`,{method:"POST",body:JSON.stringify({status:"confirmed",expectedVersion:Number(item.version||1),reason:"Confirmada por el paciente"})});setAppointments((current)=>current.map((row)=>row.id===updated.id?updated:row));}catch(e){setError(e instanceof Error?e.message:"No se pudo confirmar.");}finally{setSaving(false);}}
  function open(item:PlatformRecord){setSelected(item);setStartsAt(dateInput(item.startsAt));setEndsAt(dateInput(item.endsAt));setError("");}
  async function reschedule(event:React.FormEvent){event.preventDefault();if(!selected)return;try{setSaving(true);setError("");const updated=await platformRequest<PlatformRecord>(`/api/platform/scheduling/appointments/${selected.id}/reschedule`,{method:"POST",body:JSON.stringify({startsAt:new Date(startsAt).toISOString(),endsAt:new Date(endsAt).toISOString(),timeZone:"America/La_Paz",reason,expectedVersion:Number(selected.version||1)})});setAppointments((current)=>current.map((row)=>row.id===updated.id?updated:row));setSelected(null);}catch(e){setError(e instanceof Error?e.message:"No se pudo reprogramar.");}finally{setSaving(false);}}
  return <section className="card p-5"><h2 className="font-display font-bold">Mis próximas citas</h2>{error&&<p className="field-error mt-3" role="alert">{error}</p>}{!upcoming.length?<p className="mt-3 text-sm text-slate-500">No tienes citas próximas.</p>:<div className="mt-4 space-y-3">{upcoming.map((item)=><article className="rounded-xl border p-4 dark:border-emerald-800" key={item.id}><div className="flex justify-between gap-3"><div><strong>{String(item.title)}</strong><p className="text-sm text-slate-500">{displayDate(item.startsAt)}</p></div><StatusBadge value={item.status}/></div><div className="mt-3 flex flex-wrap gap-2">{item.status==="scheduled"&&<button className="primary-button" disabled={saving} onClick={()=>void confirm(item)}><CheckCircle2 className="h-4 w-4"/>Confirmar asistencia</button>}<button className="secondary-button" onClick={()=>open(item)}><RefreshCw className="h-4 w-4"/>Solicitar nueva fecha</button></div></article>)}</div>}{selected&&<Modal title="Reprogramar mi cita" description="La nueva fecha quedará pendiente de confirmación." onClose={()=>setSelected(null)}><form className="mt-5 grid gap-4" onSubmit={reschedule}><label>Nuevo inicio<input className="field" type="datetime-local" value={startsAt} onChange={(e)=>setStartsAt(e.target.value)}/></label><label>Nuevo fin<input className="field" type="datetime-local" value={endsAt} onChange={(e)=>setEndsAt(e.target.value)}/></label><label>Motivo<textarea className="field py-3" value={reason} onChange={(e)=>setReason(e.target.value)}/></label>{error&&<p className="field-error" role="alert">{error}</p>}<button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Reprogramar</button></form></Modal>}</section>;
}
