"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Loader2, Plus, Search } from "lucide-react";
import { usePatients } from "@/components/patients/patient-provider";
import { ConfirmDialog, EmptyState, ErrorAlert, LoadingState, Modal, Pagination, StatusBadge } from "@/components/ui/workspace-ui";
import { displayDate, platformRequest, recordList, type PlatformRecord } from "@/lib/platform-client";
import { fullName } from "@/lib/patients";

type Values=Record<string,string>;
const initial=():Values=>({patientId:"",title:"Plan nutricional",validFrom:new Date().toISOString().slice(0,10),validTo:new Date(Date.now()+6*86400000).toISOString().slice(0,10),weight:"",height:"",age:"",sex:"female",activity:"1.4",days:"7",foodId:""});
export function PlanningWorkspace(){
 const {patients,ready}=usePatients(); const [rows,setRows]=useState<PlatformRecord[]>([]),[foods,setFoods]=useState<PlatformRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[open,setOpen]=useState(false),[values,setValues]=useState<Values>(initial),[formError,setFormError]=useState(""),[saving,setSaving]=useState(false),[publishing,setPublishing]=useState<PlatformRecord|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);setError("");const [plans,catalog]=await Promise.all([platformRequest("/api/platform/planning/meal-plans"),platformRequest("/api/catalogs/alimentos")]);setRows(recordList(plans));setFoods(recordList(catalog))}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar los planes.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>rows.filter((r)=>[r.title,r.status,patients.find((p)=>p.id===r.patientId)&&fullName(patients.find((p)=>p.id===r.patientId)!)].join(" ").toLowerCase().includes(query.toLowerCase())),[rows,query,patients]);const pages=Math.max(1,Math.ceil(filtered.length/8)),visible=filtered.slice((page-1)*8,page*8);useEffect(()=>setPage(1),[query]);
 async function save(e:React.FormEvent){e.preventDefault();if(!values.patientId||!values.title.trim()){setFormError("Selecciona un paciente y escribe un título.");return}if(!values.foodId){setFormError("Agrega al menos un alimento al catálogo y selecciónalo.");return}if([values.weight,values.height,values.age].some((x)=>Number(x)<=0)){setFormError("Peso, estatura y edad deben ser mayores que cero.");return}try{setSaving(true);setFormError("");await platformRequest("/api/platform/planning/meal-plans/generate",{method:"POST",body:JSON.stringify({patientId:values.patientId,title:values.title.trim(),validFrom:values.validFrom,validTo:values.validTo,requirement:{weightKg:Number(values.weight),heightCm:Number(values.height),ageYears:Number(values.age),sex:values.sex,activityFactor:Number(values.activity),thermicEffectPercent:10,macroPercentages:{carbohydrate:50,protein:20,fat:30},nutrientTargets:[]},mealDistribution:[{mealType:"Desayuno",percentEnergy:30},{mealType:"Almuerzo",percentEnergy:40},{mealType:"Cena",percentEnergy:30}],restrictions:[],daysCount:Number(values.days),candidateItems:[{catalogType:"food",catalogId:values.foodId}]})});setOpen(false);setValues(initial());await load()}catch(e){setFormError(e instanceof Error?e.message:"No se pudo generar el plan.")}finally{setSaving(false)}}
 async function publish(){if(!publishing)return;try{setSaving(true);await platformRequest(`/api/platform/planning/meal-plans/${publishing.id}/publish`,{method:"POST",body:JSON.stringify({expectedVersion:Number(publishing.version||1)})});setPublishing(null);await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo publicar. Revisa si necesita aprobación profesional.");setPublishing(null)}finally{setSaving(false)}}
 return <section><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Planificación</p><h1 className="mt-2 font-display text-3xl font-bold">Planes nutricionales</h1><p className="mt-2 text-slate-500">Genera menús, revisa su estado y publica versiones aprobadas.</p></div><button className="primary-button" onClick={()=>{setValues(initial());setOpen(true)}}><Plus className="h-4 w-4"/>Generar plan</button></header>{error&&<ErrorAlert message={error} onRetry={()=>void load()}/>}<div className="card mt-6 overflow-hidden"><div className="border-b p-5 dark:border-emerald-800"><label className="relative block max-w-lg"><span className="sr-only">Buscar planes</span><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400"/><input className="field !mt-0 pl-11" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por plan, paciente o estado"/></label></div>{loading||!ready?<LoadingState/>:!visible.length?<EmptyState title="Sin planes" detail="Genera el primer plan nutricional para un paciente."/>:<><div className="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map((r)=><article className="rounded-xl border p-5 dark:border-emerald-800" key={r.id}><div className="flex items-start justify-between gap-2"><h2 className="font-display text-lg font-bold">{String(r.title)}</h2><StatusBadge value={r.status}/></div><p className="mt-2 text-sm text-slate-500">{patients.find((p)=>p.id===r.patientId)?fullName(patients.find((p)=>p.id===r.patientId)!):"Sin paciente"}</p><p className="mt-3 text-sm">{displayDate(r.validFrom||r.createdAt)}</p>{r.status==="draft"&&<button className="secondary-button mt-4 w-full" onClick={()=>setPublishing(r)}><CheckCircle2 className="h-4 w-4"/>Publicar</button>}</article>)}</div><Pagination page={page} pages={pages} total={filtered.length} onChange={setPage}/></>}</div>
 {open&&<Modal title="Generar plan nutricional" description="El generador usa los requerimientos y alimentos disponibles." onClose={()=>setOpen(false)}><form className="mt-6 grid gap-4" onSubmit={save} noValidate><label>Paciente *<select className="field" value={values.patientId} onChange={(e)=>setValues({...values,patientId:e.target.value})}><option value="">Selecciona un paciente</option>{patients.map((p)=><option key={p.id} value={p.id}>{fullName(p)}</option>)}</select></label><label>Título *<input className="field" value={values.title} onChange={(e)=>setValues({...values,title:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label>Válido desde<input type="date" className="field" value={values.validFrom} onChange={(e)=>setValues({...values,validFrom:e.target.value})}/></label><label>Válido hasta<input type="date" className="field" value={values.validTo} onChange={(e)=>setValues({...values,validTo:e.target.value})}/></label></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><label>Peso (kg) *<input type="number" min="1" step=".1" className="field" value={values.weight} onChange={(e)=>setValues({...values,weight:e.target.value})}/></label><label>Estatura (cm) *<input type="number" min="1" className="field" value={values.height} onChange={(e)=>setValues({...values,height:e.target.value})}/></label><label>Edad *<input type="number" min="1" className="field" value={values.age} onChange={(e)=>setValues({...values,age:e.target.value})}/></label></div><div className="grid grid-cols-2 gap-3"><label>Sexo<select className="field" value={values.sex} onChange={(e)=>setValues({...values,sex:e.target.value})}><option value="female">Femenino</option><option value="male">Masculino</option></select></label><label>Días<input type="number" min="1" max="14" className="field" value={values.days} onChange={(e)=>setValues({...values,days:e.target.value})}/></label></div><label>Alimento base *<select className="field" value={values.foodId} onChange={(e)=>setValues({...values,foodId:e.target.value})}><option value="">Selecciona un alimento</option>{foods.map((f)=><option key={f.id} value={f.id}>{String(f.name)}</option>)}</select></label>{!foods.length&&<p className="text-sm text-amber-700">Primero crea un alimento desde Catálogos → Alimentos.</p>}{formError&&<p className="field-error" role="alert">{formError}</p>}<div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{saving?"Generando…":"Generar plan"}</button></div></form></Modal>}{publishing&&<ConfirmDialog title="Publicar plan" detail="El plan quedará disponible como una versión clínica inmutable." confirmLabel="Publicar" busy={saving} onCancel={()=>setPublishing(null)} onConfirm={()=>void publish()}/>}</section>
}
