"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, History, Loader2, Plus, RefreshCw, Search } from "lucide-react";
import { usePatients } from "@/components/patients/patient-provider";
import { NutritionCalculator } from "@/components/platform/nutrition-calculator";
import { ConfirmDialog, EmptyState, ErrorAlert, LoadingState, Modal, Pagination, StatusBadge } from "@/components/ui/workspace-ui";
import { CrudPageHeader, MetricCards } from "@/components/ui/crud-ui";
import { displayDate, platformRequest, recordList, type PlatformRecord } from "@/lib/platform-client";
import { fullName } from "@/lib/patients";
import type { NutritionInputs } from "@/lib/nutrition-calculations";

type Values = { patientId:string; title:string; validFrom:string; validTo:string; days:number; foodIds:string[]; restrictions:string; nutrition:NutritionInputs };
const initial = (): Values => ({ patientId:"", title:"Plan nutricional", validFrom:new Date().toISOString().slice(0,10), validTo:new Date(Date.now()+6*86400000).toISOString().slice(0,10), days:7, foodIds:[], restrictions:"", nutrition:{weightKg:70,heightCm:170,ageYears:30,sex:"female",activityFactor:1.55,thermicEffectPercent:10,carbohydratePercent:50,proteinPercent:20,fatPercent:30} });
const parseRestrictions = (text:string) => text.split(",").map((value)=>value.trim()).filter(Boolean).map((value)=>({type:"allergy",value}));

export function PlanningWorkspace() {
  const { patients, ready } = usePatients();
  const [rows,setRows]=useState<PlatformRecord[]>([]),[foods,setFoods]=useState<PlatformRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1);
  const [open,setOpen]=useState(false),[values,setValues]=useState<Values>(initial),[formError,setFormError]=useState(""),[saving,setSaving]=useState(false),[publishing,setPublishing]=useState<PlatformRecord|null>(null);
  const [versionsFor,setVersionsFor]=useState<PlatformRecord|null>(null),[versions,setVersions]=useState<PlatformRecord[]>([]),[versionsLoading,setVersionsLoading]=useState(false);
  const [substitution,setSubstitution]=useState<PlatformRecord|null>(null),[originalId,setOriginalId]=useState(""),[candidateIds,setCandidateIds]=useState<string[]>([]),[subRestrictions,setSubRestrictions]=useState(""),[alternatives,setAlternatives]=useState<PlatformRecord[]>([]);
  const load=useCallback(async()=>{try{setLoading(true);setError("");const [plans,catalog]=await Promise.all([platformRequest("/api/platform/planning/meal-plans"),platformRequest("/api/catalogs/alimentos")]);setRows(recordList(plans));setFoods(recordList(catalog));}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar los planes.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>rows.filter((row)=>[row.title,row.status,patients.find((p)=>p.id===row.patientId)&&fullName(patients.find((p)=>p.id===row.patientId)!)].join(" ").toLowerCase().includes(query.toLowerCase())),[rows,query,patients]);
  const pages=Math.max(1,Math.ceil(filtered.length/8)),visible=filtered.slice((page-1)*8,page*8); useEffect(()=>setPage(1),[query]);
  const selectedFoods=foods.filter((food)=>values.foodIds.includes(food.id));
  function toggleFood(id:string){setValues((current)=>({...current,foodIds:current.foodIds.includes(id)?current.foodIds.filter((item)=>item!==id):[...current.foodIds,id]}));}
  async function save(event:React.FormEvent){event.preventDefault();const n=values.nutrition;if(!values.patientId||!values.title.trim()){setFormError("Selecciona un paciente y escribe un título.");return;}if(!values.foodIds.length){setFormError("Selecciona al menos un alimento.");return;}if([n.weightKg,n.heightCm,n.ageYears].some((x)=>x<=0)){setFormError("Peso, estatura y edad deben ser mayores que cero.");return;}if(n.carbohydratePercent+n.proteinPercent+n.fatPercent!==100){setFormError("Los macronutrientes deben sumar 100%.");return;}try{setSaving(true);setFormError("");await platformRequest("/api/platform/planning/meal-plans/generate",{method:"POST",body:JSON.stringify({patientId:values.patientId,title:values.title.trim(),validFrom:values.validFrom,validTo:values.validTo,requirement:{weightKg:n.weightKg,heightCm:n.heightCm,ageYears:n.ageYears,sex:n.sex,activityFactor:n.activityFactor,thermicEffectPercent:n.thermicEffectPercent,macroPercentages:{carbohydrate:n.carbohydratePercent,protein:n.proteinPercent,fat:n.fatPercent},nutrientTargets:[]},mealDistribution:[{mealType:"Desayuno",percentEnergy:25},{mealType:"Almuerzo",percentEnergy:40},{mealType:"Merienda",percentEnergy:10},{mealType:"Cena",percentEnergy:25}],restrictions:parseRestrictions(values.restrictions),daysCount:values.days,candidateItems:values.foodIds.map((catalogId)=>({catalogType:"food",catalogId}))})});setOpen(false);setValues(initial());await load();}catch(e){setFormError(e instanceof Error?e.message:"No se pudo generar el plan.");}finally{setSaving(false);}}
  async function publish(){if(!publishing)return;try{setSaving(true);await platformRequest(`/api/platform/planning/meal-plans/${publishing.id}/publish`,{method:"POST",body:JSON.stringify({expectedVersion:Number(publishing.version||1)})});setPublishing(null);await load();}catch(e){setError(e instanceof Error?e.message:"No se pudo publicar.");setPublishing(null);}finally{setSaving(false);}}
  async function showVersions(row:PlatformRecord){setVersionsFor(row);setVersionsLoading(true);try{setVersions(recordList(await platformRequest(`/api/platform/planning/meal-plans/${row.id}/versions`)));}catch(e){setError(e instanceof Error?e.message:"No se cargaron las versiones.");setVersionsFor(null);}finally{setVersionsLoading(false);}}
  function startSubstitution(row:PlatformRecord){setSubstitution(row);setOriginalId(foods[0]?.id||"");setCandidateIds([]);setSubRestrictions("");setAlternatives([]);}
  async function evaluateSubstitution(event:React.FormEvent){event.preventDefault();if(!originalId||!candidateIds.length){setFormError("Selecciona el alimento original y al menos una alternativa.");return;}try{setSaving(true);setFormError("");const result=await platformRequest<{alternatives:PlatformRecord[]}>("/api/platform/planning/substitutions/evaluate",{method:"POST",body:JSON.stringify({patientId:substitution?.patientId,original:{catalogType:"food",catalogId:originalId,amount:100,amountUnit:"g"},candidates:candidateIds.map((catalogId)=>({catalogType:"food",catalogId})),restrictions:parseRestrictions(subRestrictions)})});setAlternatives(result.alternatives||[]);}catch(e){setFormError(e instanceof Error?e.message:"No se pudo evaluar la sustitución.");}finally{setSaving(false);}}
  return <section>
    <CrudPageHeader eyebrow="Planificación avanzada" title="Planes nutricionales" description="Genera planes calculados, conserva versiones y encuentra sustituciones seguras." action={<button className="primary-button" onClick={()=>{setValues(initial());setOpen(true);}}><Plus className="h-4 w-4"/>Generar plan</button>}/>
    <MetricCards metrics={[{label:"Planes",value:rows.length,detail:"Versiones principales"},{label:"Publicados",value:rows.filter((row)=>row.status==="published").length,detail:"Disponibles para pacientes",tone:"blue"},{label:"Borradores",value:rows.filter((row)=>row.status==="draft").length,detail:"Pendientes de revisión",tone:"amber"},{label:"Alimentos",value:foods.length,detail:"Opciones del catálogo",tone:"slate"}]}/>
    {error&&<ErrorAlert message={error} onRetry={()=>void load()}/>}<div className="card mt-6 overflow-hidden"><div className="border-b p-5 dark:border-emerald-800"><label className="relative block max-w-lg"><span className="sr-only">Buscar planes</span><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400"/><input className="field !mt-0 pl-11" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por plan, paciente o estado"/></label></div>{loading||!ready?<LoadingState/>:!visible.length?<EmptyState title="Sin planes" detail="Genera el primer plan nutricional para un paciente."/>:<><div className="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map((row)=><article className="rounded-xl border p-5 dark:border-emerald-800" key={row.id}><div className="flex items-start justify-between gap-2"><h2 className="font-display text-lg font-bold">{String(row.title)}</h2><StatusBadge value={row.status}/></div><p className="mt-2 text-sm text-slate-500">{patients.find((p)=>p.id===row.patientId)?fullName(patients.find((p)=>p.id===row.patientId)!):"Paciente"}</p><p className="mt-3 text-sm">{displayDate(row.validFrom||row.createdAt)} · v{String(row.version||1)}</p><div className="mt-4 grid gap-2"><button className="secondary-button" onClick={()=>void showVersions(row)}><History className="h-4 w-4"/>Ver versiones</button><button className="secondary-button" onClick={()=>startSubstitution(row)}><RefreshCw className="h-4 w-4"/>Sustituir alimento</button>{row.status==="draft"&&<button className="primary-button" onClick={()=>setPublishing(row)}><CheckCircle2 className="h-4 w-4"/>Publicar</button>}</div></article>)}</div><Pagination page={page} pages={pages} total={filtered.length} onChange={setPage}/></>}</div>
    {open&&<Modal title="Generar plan nutricional" description="Los cálculos, alergias y restricciones se validan antes de proponer el menú." onClose={()=>setOpen(false)}><form className="mt-6 grid gap-5" onSubmit={save} noValidate><label>Paciente *<select className="field" value={values.patientId} onChange={(e)=>setValues({...values,patientId:e.target.value})}><option value="">Selecciona un paciente</option>{patients.map((p)=><option key={p.id} value={p.id}>{fullName(p)}</option>)}</select></label><label>Título *<input className="field" value={values.title} onChange={(e)=>setValues({...values,title:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label>Válido desde<input type="date" className="field" value={values.validFrom} onChange={(e)=>setValues({...values,validFrom:e.target.value})}/></label><label>Válido hasta<input type="date" className="field" value={values.validTo} onChange={(e)=>setValues({...values,validTo:e.target.value})}/></label></div><NutritionCalculator value={values.nutrition} onChange={(nutrition)=>setValues({...values,nutrition})}/><label>Alergias y restricciones <span className="text-slate-400">(separadas por coma)</span><input className="field" value={values.restrictions} onChange={(e)=>setValues({...values,restrictions:e.target.value})} placeholder="maní, lactosa, gluten"/></label><fieldset><legend className="font-semibold">Alimentos candidatos *</legend><div className="mt-2 grid max-h-40 gap-2 overflow-y-auto rounded-xl border p-3 dark:border-emerald-800">{foods.map((food)=><label className="flex items-center gap-2 text-sm" key={food.id}><input type="checkbox" checked={values.foodIds.includes(food.id)} onChange={()=>toggleFood(food.id)}/>{String(food.name||food.title)}</label>)}</div><small className="text-slate-500">{selectedFoods.length} seleccionados · el generador excluye los incompatibles.</small></fieldset><label>Días<input className="field" type="number" min="1" max="14" value={values.days} onChange={(e)=>setValues({...values,days:Number(e.target.value)})}/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{saving?"Generando…":"Generar plan"}</button></div></form></Modal>}
    {versionsFor&&<Modal title={`Versiones de ${String(versionsFor.title)}`} description="Cada publicación conserva una copia clínica inmutable." onClose={()=>setVersionsFor(null)}>{versionsLoading?<LoadingState/>:!versions.length?<EmptyState title="Sin versiones publicadas" detail="Publica el plan para crear la primera versión."/>:<ol className="mt-5 space-y-3">{versions.map((version)=><li className="rounded-xl border p-4 dark:border-emerald-800" key={version.id}><strong>Versión {String(version.version)}</strong><p className="text-sm text-slate-500">Publicada {displayDate(version.publishedAt)}</p></li>)}</ol>}</Modal>}
    {substitution&&<Modal title="Sustitución segura" description="Compara el aporte nutricional y descarta alternativas que infringen alergias o restricciones." onClose={()=>setSubstitution(null)}><form className="mt-5 grid gap-4" onSubmit={evaluateSubstitution}><label>Alimento original<select className="field" value={originalId} onChange={(e)=>setOriginalId(e.target.value)}><option value="">Selecciona</option>{foods.map((food)=><option value={food.id} key={food.id}>{String(food.name||food.title)}</option>)}</select></label><fieldset><legend className="font-semibold">Alternativas</legend><div className="mt-2 grid max-h-36 gap-2 overflow-y-auto rounded-xl border p-3 dark:border-emerald-800">{foods.filter((food)=>food.id!==originalId).map((food)=><label className="flex gap-2 text-sm" key={food.id}><input type="checkbox" checked={candidateIds.includes(food.id)} onChange={()=>setCandidateIds((current)=>current.includes(food.id)?current.filter((id)=>id!==food.id):[...current,food.id])}/>{String(food.name||food.title)}</label>)}</div></fieldset><label>Alergias y restricciones<input className="field" value={subRestrictions} onChange={(e)=>setSubRestrictions(e.target.value)} placeholder="maní, lactosa, gluten"/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Evaluar alternativas</button></form>{alternatives.length>0&&<div className="mt-5 space-y-2" aria-live="polite"><h3 className="font-semibold">Alternativas compatibles</h3>{alternatives.map((item)=><article className="flex items-center justify-between rounded-xl bg-emerald-50 p-3 text-sm dark:bg-emerald-950" key={String(item.catalogId)}><span><b>{String(item.name)}</b><br/>{String(item.amount)} {String(item.amountUnit)}</span><strong>{String(item.similarityScore)}% similar</strong></article>)}</div>}</Modal>}
    {publishing&&<ConfirmDialog title="Publicar plan" detail="El plan quedará disponible como una versión clínica inmutable." confirmLabel="Publicar" busy={saving} onCancel={()=>setPublishing(null)} onConfirm={()=>void publish()}/>}
  </section>;
}
