"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, History, Loader2, Plus, RefreshCw, Search, XCircle } from "lucide-react";
import { usePatients } from "@/components/patients/patient-provider";
import { ConfirmDialog, EmptyState, ErrorAlert, LoadingState, Modal, Pagination, StatusBadge } from "@/components/ui/workspace-ui";
import { dateInput, displayDate, platformRequest, recordList, type PlatformRecord } from "@/lib/platform-client";
import { fullName } from "@/lib/patients";

type Form={patientId:string;title:string;type:string;startsAt:string;endsAt:string;location:string;notes:string};
const empty=():Form=>({patientId:"",title:"Consulta nutricional",type:"follow_up",startsAt:dateInput(new Date(Date.now()+86400000)),endsAt:dateInput(new Date(Date.now()+90000000)),location:"Consultorio",notes:""});
export function SchedulingWorkspace(){
 const {patients,ready}=usePatients(); const [rows,setRows]=useState<PlatformRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[page,setPage]=useState(1);
 const [creating,setCreating]=useState(false),[form,setForm]=useState<Form>(empty),[saving,setSaving]=useState(false),[formError,setFormError]=useState(""),[action,setAction]=useState<{row:PlatformRecord;kind:"confirm"|"cancel"}|null>(null);
 const [rescheduling,setRescheduling]=useState<PlatformRecord|null>(null),[newStart,setNewStart]=useState(""),[newEnd,setNewEnd]=useState(""),[reason,setReason]=useState("Cambio solicitado por el paciente"),[historyFor,setHistoryFor]=useState<PlatformRecord|null>(null),[history,setHistory]=useState<PlatformRecord[]>([]);
 const load=useCallback(async()=>{try{setLoading(true);setError("");setRows(recordList(await platformRequest("/api/platform/scheduling/appointments")));}catch(e){setError(e instanceof Error?e.message:"No se cargó la agenda.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const filtered=useMemo(()=>rows.filter((r)=>[r.title,r.status,patients.find((p)=>p.id===r.patientId)&&fullName(patients.find((p)=>p.id===r.patientId)!)].join(" ").toLowerCase().includes(query.toLowerCase())&&(status==="all"||r.status===status)),[rows,query,status,patients]); const pages=Math.max(1,Math.ceil(filtered.length/8)),visible=filtered.slice((page-1)*8,page*8);useEffect(()=>setPage(1),[query,status]);
 async function create(event:React.FormEvent){event.preventDefault();if(!form.patientId||!form.title.trim()){setFormError("Selecciona un paciente y escribe el título.");return;}if(new Date(form.endsAt)<=new Date(form.startsAt)){setFormError("La hora final debe ser posterior al inicio.");return;}try{setSaving(true);setFormError("");await platformRequest("/api/platform/scheduling/appointments",{method:"POST",body:JSON.stringify({patientId:form.patientId,title:form.title,type:form.type,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),timeZone:"America/La_Paz",location:form.location||null,notes:form.notes||null})});setCreating(false);setForm(empty());await load();}catch(e){setFormError(e instanceof Error?e.message:"No se creó la cita.");}finally{setSaving(false);}}
 async function changeStatus(){if(!action)return;try{setSaving(true);await platformRequest(`/api/platform/scheduling/appointments/${action.row.id}/status`,{method:"POST",body:JSON.stringify({status:action.kind==="confirm"?"confirmed":"cancelled",reason:action.kind==="cancel"?"Cancelada desde la agenda":null,expectedVersion:Number(action.row.version||1)})});setAction(null);await load();}catch(e){setError(e instanceof Error?e.message:"No se actualizó la cita.");setAction(null);}finally{setSaving(false);}}
 function openReschedule(row:PlatformRecord){setRescheduling(row);setNewStart(dateInput(row.startsAt));setNewEnd(dateInput(row.endsAt));setReason("Cambio solicitado por el paciente");setFormError("");}
 async function reschedule(event:React.FormEvent){event.preventDefault();if(!rescheduling)return;try{setSaving(true);setFormError("");await platformRequest(`/api/platform/scheduling/appointments/${rescheduling.id}/reschedule`,{method:"POST",body:JSON.stringify({startsAt:new Date(newStart).toISOString(),endsAt:new Date(newEnd).toISOString(),timeZone:"America/La_Paz",reason,expectedVersion:Number(rescheduling.version||1)})});setRescheduling(null);await load();}catch(e){setFormError(e instanceof Error?e.message:"No se reprogramó la cita.");}finally{setSaving(false);}}
 async function showHistory(row:PlatformRecord){setHistoryFor(row);try{setHistory(recordList(await platformRequest(`/api/platform/scheduling/appointments/${row.id}/history`)));}catch(e){setError(e instanceof Error?e.message:"No se cargó el historial.");setHistoryFor(null);}}
 return <section><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Agenda y recordatorios</p><h1 className="mt-2 font-display text-3xl font-bold">Agenda</h1><p className="mt-2 text-slate-500">Programa, confirma y reprograma citas con historial auditable y recordatorios automáticos.</p></div><button className="primary-button" onClick={()=>{setForm(empty());setCreating(true);}}><Plus className="h-4 w-4"/>Nueva cita</button></header>{error&&<ErrorAlert message={error} onRetry={()=>void load()}/>}<div className="card mt-6 overflow-hidden"><div className="grid gap-3 border-b p-5 sm:grid-cols-[1fr_13rem]"><label className="relative"><span className="sr-only">Buscar citas</span><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400"/><input className="field !mt-0 pl-11" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar cita o paciente"/></label><select aria-label="Filtrar citas por estado" className="field !mt-0" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">Todos los estados</option><option value="scheduled">Pendientes</option><option value="confirmed">Confirmadas</option><option value="completed">Completadas</option><option value="cancelled">Canceladas</option></select></div>{loading||!ready?<LoadingState/>:!visible.length?<EmptyState title="Sin citas" detail="Crea una cita o cambia los filtros."/>:<><div className="grid gap-4 p-4 lg:grid-cols-2">{visible.map((row)=><article className="rounded-xl border p-5 dark:border-emerald-800" key={row.id}><div className="flex justify-between gap-3"><div><h2 className="font-display text-lg font-bold">{String(row.title)}</h2><p className="text-sm text-slate-500">{patients.find((p)=>p.id===row.patientId)?fullName(patients.find((p)=>p.id===row.patientId)!):"Paciente"}</p></div><StatusBadge value={row.status}/></div><p className="mt-3 font-semibold">{displayDate(row.startsAt)}</p><p className="text-sm text-slate-500">{String(row.location||"Sin ubicación")}</p><div className="mt-4 flex flex-wrap gap-2"><button className="secondary-button" onClick={()=>void showHistory(row)}><History className="h-4 w-4"/>Historial</button>{["scheduled","confirmed"].includes(String(row.status))&&<button className="secondary-button" onClick={()=>openReschedule(row)}><RefreshCw className="h-4 w-4"/>Reprogramar</button>}{row.status==="scheduled"&&<button className="primary-button" onClick={()=>setAction({row,kind:"confirm"})}><CheckCircle2 className="h-4 w-4"/>Confirmar</button>}{["scheduled","confirmed"].includes(String(row.status))&&<button className="danger-button" onClick={()=>setAction({row,kind:"cancel"})}><XCircle className="h-4 w-4"/>Cancelar</button>}</div></article>)}</div><Pagination page={page} pages={pages} total={filtered.length} onChange={setPage}/></>}</div>
 {creating&&<Modal title="Nueva cita" description="Se crearán recordatorios según las preferencias del paciente." onClose={()=>setCreating(false)}><form className="mt-5 grid gap-4" onSubmit={create}><label>Paciente *<select className="field" value={form.patientId} onChange={(e)=>setForm({...form,patientId:e.target.value})}><option value="">Selecciona</option>{patients.map((p)=><option value={p.id} key={p.id}>{fullName(p)}</option>)}</select></label><label>Título *<input className="field" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></label><label>Tipo<select className="field" value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}><option value="initial">Inicial</option><option value="follow_up">Seguimiento</option><option value="control">Control</option><option value="sports">Deportiva</option><option value="other">Otra</option></select></label><div className="grid grid-cols-2 gap-3"><label>Inicio *<input type="datetime-local" className="field" value={form.startsAt} onChange={(e)=>setForm({...form,startsAt:e.target.value})}/></label><label>Fin *<input type="datetime-local" className="field" value={form.endsAt} onChange={(e)=>setForm({...form,endsAt:e.target.value})}/></label></div><label>Ubicación<input className="field" value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></label><label>Notas<textarea className="field py-3" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Guardar cita</button></form></Modal>}
 {rescheduling&&<Modal title="Reprogramar cita" description="Los recordatorios pendientes se reemplazarán por la nueva fecha." onClose={()=>setRescheduling(null)}><form className="mt-5 grid gap-4" onSubmit={reschedule}><div className="grid grid-cols-2 gap-3"><label>Nuevo inicio<input type="datetime-local" className="field" value={newStart} onChange={(e)=>setNewStart(e.target.value)}/></label><label>Nuevo fin<input type="datetime-local" className="field" value={newEnd} onChange={(e)=>setNewEnd(e.target.value)}/></label></div><label>Motivo *<textarea className="field py-3" value={reason} onChange={(e)=>setReason(e.target.value)}/></label>{formError&&<p className="field-error" role="alert">{formError}</p>}<button className="primary-button" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Confirmar reprogramación</button></form></Modal>}
 {historyFor&&<Modal title={`Historial de ${String(historyFor.title)}`} onClose={()=>setHistoryFor(null)}>{!history.length?<EmptyState title="Sin cambios" detail="No hay cambios registrados."/>:<ol className="mt-5 space-y-3">{history.map((item,index)=><li className="border-l-2 border-emerald-500 pl-4" key={`${item.changedAt}-${index}`}><strong>{String(item.newStatus).replaceAll("_"," ")}</strong><p className="text-sm text-slate-500">{String(item.reason||"Cambio de estado")}</p><small>{displayDate(item.changedAt)}</small></li>)}</ol>}</Modal>}
 {action&&<ConfirmDialog title={action.kind==="confirm"?"Confirmar cita":"Cancelar cita"} detail={`Se registrará el cambio de “${String(action.row.title)}” en el historial.`} confirmLabel={action.kind==="confirm"?"Confirmar":"Cancelar cita"} busy={saving} onCancel={()=>setAction(null)} onConfirm={()=>void changeStatus()}/>} 
 </section>;
}
