IF DB_ID('Nutrimejor') IS NULL CREATE DATABASE Nutrimejor;
GO
USE Nutrimejor;
GO

CREATE TABLE Usuarios (
  IdUsuario INT IDENTITY PRIMARY KEY,
  Nombre NVARCHAR(120) NOT NULL,
  Email NVARCHAR(180) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  Rol VARCHAR(20) NOT NULL DEFAULT 'NUTRICIONISTA' CHECK (Rol IN ('ADMIN','NUTRICIONISTA')),
  Matricula NVARCHAR(80) NULL,
  Especialidad NVARCHAR(120) NULL,
  Activo BIT NOT NULL DEFAULT 1,
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE Pacientes (
  IdPaciente INT IDENTITY PRIMARY KEY,
  IdNutricionista INT NOT NULL REFERENCES Usuarios(IdUsuario),
  Nombres NVARCHAR(100) NOT NULL,
  Apellidos NVARCHAR(100) NOT NULL,
  Documento NVARCHAR(30) NULL,
  FechaNacimiento DATE NULL,
  Sexo VARCHAR(20) NULL,
  Telefono NVARCHAR(30) NULL,
  Email NVARCHAR(180) NULL,
  Objetivo NVARCHAR(300) NULL,
  Peso DECIMAL(6,2) NULL,
  Altura DECIMAL(5,2) NULL,
  Estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (Estado IN ('ACTIVO','INACTIVO')),
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  FechaActualizacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
CREATE INDEX IX_Pacientes_Nutricionista ON Pacientes(IdNutricionista, Estado);
GO

CREATE TABLE Alimentos (
  IdAlimento INT IDENTITY PRIMARY KEY,
  IdNutricionista INT NOT NULL REFERENCES Usuarios(IdUsuario),
  Nombre NVARCHAR(150) NOT NULL,
  PorcionGramos DECIMAL(7,2) NOT NULL DEFAULT 100,
  Calorias DECIMAL(8,2) NOT NULL DEFAULT 0,
  Proteinas DECIMAL(8,2) NOT NULL DEFAULT 0,
  Carbohidratos DECIMAL(8,2) NOT NULL DEFAULT 0,
  Grasas DECIMAL(8,2) NOT NULL DEFAULT 0,
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE Recetas (
  IdReceta INT IDENTITY PRIMARY KEY,
  IdNutricionista INT NOT NULL REFERENCES Usuarios(IdUsuario),
  Nombre NVARCHAR(150) NOT NULL,
  Descripcion NVARCHAR(500) NULL,
  Porciones INT NOT NULL DEFAULT 1,
  Calorias DECIMAL(8,2) NOT NULL DEFAULT 0,
  Ingredientes NVARCHAR(MAX) NULL,
  Preparacion NVARCHAR(MAX) NULL,
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE Dietas (
  IdDieta INT IDENTITY PRIMARY KEY,
  IdNutricionista INT NOT NULL REFERENCES Usuarios(IdUsuario),
  IdPaciente INT NULL REFERENCES Pacientes(IdPaciente),
  Nombre NVARCHAR(150) NOT NULL,
  ObjetivoCalorias DECIMAL(8,2) NULL,
  Descripcion NVARCHAR(MAX) NULL,
  Estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR' CHECK (Estado IN ('BORRADOR','ACTIVA','FINALIZADA')),
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
