IF DB_ID('Nutrimejor') IS NULL CREATE DATABASE Nutrimejor;
GO
USE Nutrimejor;
GO
CREATE TABLE Usuarios(IdUsuario INT IDENTITY PRIMARY KEY,Nombre NVARCHAR(120) NOT NULL,Email NVARCHAR(180) NOT NULL UNIQUE,PasswordHash NVARCHAR(255) NOT NULL,Rol VARCHAR(20) NOT NULL DEFAULT 'NUTRICIONISTA' CHECK(Rol IN('ADMIN','NUTRICIONISTA')),Activo BIT NOT NULL DEFAULT 1,FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Pacientes(IdPaciente UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),IdNutricionista INT NOT NULL REFERENCES Usuarios(IdUsuario),Nombres NVARCHAR(100) NOT NULL,Apellidos NVARCHAR(100) NOT NULL,Documento NVARCHAR(30),FechaNacimiento DATE,Sexo NVARCHAR(20),Telefono NVARCHAR(30),Email NVARCHAR(180),Objetivo NVARCHAR(300),Peso DECIMAL(6,2),Altura DECIMAL(6,2),Estado VARCHAR(20) NOT NULL DEFAULT 'Activo',FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FechaActualizacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE INDEX IX_Pacientes_Propietario ON Pacientes(IdNutricionista,Estado);
CREATE TABLE HistorialPaciente(IdHistorial UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),IdPaciente UNIQUEIDENTIFIER NOT NULL REFERENCES Pacientes(IdPaciente) ON DELETE CASCADE,Tipo NVARCHAR(60) NOT NULL,Notas NVARCHAR(MAX) NOT NULL,Fecha DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Catalogos(IdCatalogo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),IdNutricionista INT NOT NULL REFERENCES Usuarios(IdUsuario),Tipo VARCHAR(20) NOT NULL CHECK(Tipo IN('recetas','alimentos','dietas')),Nombre NVARCHAR(150) NOT NULL,Descripcion NVARCHAR(1000),Calorias DECIMAL(9,2) DEFAULT 0,Extra NVARCHAR(250),FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE INDEX IX_Catalogos_Propietario ON Catalogos(IdNutricionista,Tipo);
GO
