import { CalendarDays, ClipboardList, FileText, Ruler, Target } from "lucide-react";
import { redirect } from "next/navigation";
import { callService, type ServiceName } from "@/lib/server/service-client";

type Item = Record<string, unknown> & { id:string };
async function collection(service:ServiceName,path:string):Promise<Item[]> { try { const response=await callService(service,path); if(!response.ok)return []; const value=await response.json(); return Array.isArray(value)?value:[]; } catch { return []; } }

export default async function PatientPortal() {
  const session=await callService("identity","/v1/sessions/me"); if(!session.ok) redirect("/login"); const {user}=await session.json();
  if(user.organizationRole!=="PATIENT") redirect("/dashboard");
  if(!user.patientId) return <div className="card p-8"><h1 className="font-display text-2xl font-bold">Portal del paciente</h1><p className="mt-2 text-slate-500">Tu cuenta todavía no está vinculada a una ficha clínica. Solicita al consultorio que complete la vinculación.</p></div>;
  const patientId=String(user.patientId);
  const [measurements,plans,appointments,documents,consultations]=await Promise.all([
    collection("measurements",`/v1/measurement-sessions?patientId=${patientId}`), collection("planning",`/v1/meal-plans?patientId=${patientId}`), collection("scheduling",`/v1/appointments?patientId=${patientId}`), collection("documents",`/v1/generated-documents?patientId=${patientId}`), collection("clinical",`/v1/consultations?patientId=${patientId}`),
  ]);
  const latestMeasurement=measurements[0], activePlan=plans.find((item)=>item.status==="published")||plans[0], nextAppointment=appointments.filter((item)=>new Date(String(item.startsAt||0)).getTime()>=Date.now()).sort((a,b)=>String(a.startsAt).localeCompare(String(b.startsAt)))[0];
  const stats=[[Ruler,measurements.length,"Controles registrados"],[ClipboardList,plans.filter((item)=>item.status==="published").length,"Planes disponibles"],[CalendarDays,appointments.length,"Citas"],[FileText,documents.filter((item)=>item.status==="completed").length,"Documentos"]] as const;
  return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-br from-emerald-700 to-emerald-950 p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-emerald-200">Mi espacio</p><h1 className="mt-2 font-display text-3xl font-bold">Hola, {user.name}</h1><p className="mt-2 max-w-xl text-emerald-100">Consulta tu progreso, el plan indicado por tu nutricionista y tus próximas citas.</p></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([Icon,value,label])=><article className="card flex items-center gap-4 p-5" key={label}><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950"><Icon/></span><div><strong className="font-display text-2xl">{value}</strong><p className="text-xs text-slate-500">{label}</p></div></article>)}</section><section className="grid gap-5 lg:grid-cols-3"><article className="card p-5"><h2 className="flex items-center gap-2 font-display font-bold"><Ruler className="h-5 w-5 text-emerald-700"/>Último control</h2>{latestMeasurement?<><p className="mt-4 font-semibold">{String(latestMeasurement.title)}</p><p className="text-sm text-slate-500">{formatDate(latestMeasurement.recordedAt||latestMeasurement.createdAt)}</p></>:<p className="mt-4 text-sm text-slate-500">Aún no hay mediciones.</p>}</article><article className="card p-5"><h2 className="flex items-center gap-2 font-display font-bold"><ClipboardList className="h-5 w-5 text-emerald-700"/>Plan actual</h2>{activePlan?<><p className="mt-4 font-semibold">{String(activePlan.title)}</p><p className="text-sm text-slate-500">Estado: {String(activePlan.status)}</p></>:<p className="mt-4 text-sm text-slate-500">Tu plan todavía no fue publicado.</p>}</article><article className="card p-5"><h2 className="flex items-center gap-2 font-display font-bold"><CalendarDays className="h-5 w-5 text-emerald-700"/>Próxima cita</h2>{nextAppointment?<><p className="mt-4 font-semibold">{String(nextAppointment.title)}</p><p className="text-sm text-slate-500">{formatDate(nextAppointment.startsAt)}</p></>:<p className="mt-4 text-sm text-slate-500">No tienes citas próximas.</p>}</article></section><section className="card p-5"><h2 className="flex items-center gap-2 font-display font-bold"><Target className="h-5 w-5 text-emerald-700"/>Tu proceso clínico</h2><p className="mt-3 text-sm text-slate-500">Tienes {consultations.length} consultas registradas. La información clínica se muestra en modo lectura y solo corresponde a tu propia ficha.</p></section></div>;
}
function formatDate(value:unknown){if(!value)return "Sin fecha";return new Intl.DateTimeFormat("es-BO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(value)));}
